//ProfilePage
export const ADD_POST = "ADD_POST"
export const DELETE_POST = "DELETE_POST"
export const SET_USERS_PROFILE = "SET_USERS_PROFILE"
export const SET_STATUS = "SET_STATUS"
export const UPDATE_STATUS = "UPDATE_STATUS"
//DialogsPage
export const ADD_MESSAGE = "ADD_MESSAGE"
//UsersPage
export const SET_USERS_DATA = "SET_USERS_DATA"
export const FOLLOW = "FOLLOW"
export const UNFOLLOW = "UNFOLLOW"
export const SET_USERS = "SET_USERS"
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE"
export const SET_TOTAL_USERS_COUNT = "SET_TOTAL_USERS_COUNT"
export const TOGGLE_IS_FETCHING = "TOGGLE_IS_FETCHING"
export const TOGGLE_IS_FOLLOWING_PROGRESS = "TOGGLE_IS_FOLLOWING_PROGRESS"